Add log4j2-api into the build.gradle
merceneryinbox/EpamMarket pull request #70
Opened 2017-12-21 23:43 UTC by merceneryinbox

2017-12-21 23:47 UTC, merceneryinbox commented
.... нууу не знаю не знаю , у меня всё билдится,  кроме захардкоденого пароля ошибок нет...

2017-12-22 13:15 UTC, vladimirshefer requested changes

2017-12-22 13:15 UTC, vladimirshefer commented on src/main/java/apps/Main.java
> +	public static void main(String[] args) {
Auto reformatting required

2017-12-22 13:15 UTC, vladimirshefer commented on src/main/java/dao/PostgresCartDAO.java
> +				resultSet.close();
Use try-with-resources

2017-12-22 14:07 UTC, vladimirshefer approved these changes

2017-12-22 14:07 UTC, merged